[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
description = "Cardano smart contract language and toolchain"
documentation = "https://aiken-lang.org"
version = "1.1.23"
edition = "2024"
repository = "https://github.com/aiken-lang/aiken"
homepage = "https://github.com/aiken-lang/aiken"
license = "Apache-2.0"
authors = [
    "Lucas Rosa <x@rvcas.dev>",
    "Kasey White <kwhitemsg@gmail.com>",
    "KtorZ <matthias.benkort@gmail.com>",
]
rust-version = "1.94.1" # If changing, also change in workflow/release.yml

[workspace.metadata.release]
shared-version = true
tag-name = "v{{version}}"

# Config for 'cargo dist'
[workspace.metadata.dist]
# The preferred cargo-dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.22.1"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["shell", "powershell", "npm", "homebrew"]
# A GitHub repo to push Homebrew formulas to
tap = "aiken-lang/homebrew-tap"
# Target platforms to build apps for (Rust target-triple syntax)
targets = [
    "aarch64-apple-darwin",
    "x86_64-apple-darwin",
    "x86_64-unknown-linux-musl",
    "aarch64-unknown-linux-musl",
    "x86_64-pc-windows-msvc",
]
# The archive format to use for windows builds (defaults .zip)
windows-archive = ".tar.gz"
# The archive format to use for non-windows builds (defaults .tar.xz)
unix-archive = ".tar.gz"
# A namespace to use when publishing this package to the npm registry
npm-scope = "@aiken-lang"
# Publish jobs to run in CI
publish-jobs = ["homebrew", "npm"]
# Which actions to run on pull requests
pr-run-mode = "plan"
# Whether to install an updater program
install-updater = false
# Path that installers should place binaries in
install-path = "~/.aiken/bin"
# Whether to publish prereleases to package managers
publish-prereleases = true
# Inject build steps into the build-local-artifacts job to prepare the container.
# This is needed to install libssl-dev and musl tools for producing statically linked
# binary on Linux and avoid weird segfaults.
#
# Note: should be a path relative to the .github/workflows/ directory, and
# which should point to a .yml file containing the github workflow steps just
# as one would normally write them in a workflow.
github-build-setup = "../musl-build-setup.yml"

# Cargo-dist uses ubuntu-20.04 by default, causing issues in various cases
# because it links with openssl-1.1 whereas recent distro ships with 3.x
[workspace.metadata.dist.github-custom-runners]
aarch64-unknown-linux-musl = "ubuntu-24.04-arm"
x86_64-unknown-linux-musl = "ubuntu-24.04"
x86_64-pc-windows-msvc = "windows-2022"
x86_64-apple-darwin = "macos-15-intel"
aarch64-apple-darwin = "macos-15"

[workspace.dependencies]
askama = "0.12.0"
bitvec = "1.0.1"
blst = "0.3.17"
built = "0.7.1"
camino = "1.1.9"
chumsky = { version = "0.9.2", default-features = false }
ciborium = "0.2.2"
clap = "4.5.60"
clap_complete = "4.5.61"
color-print = "0.3.7"
crossbeam-channel = "0.5.15"
cryptoxide = "0.6.3"
difference = "2.0.0"
dirs = "6.0.0"
fslock = "0.2.1"
futures = "0.3.26"
glob = "0.3.3"
hamming = "0.1.3"
hex = "0.4.3"
ignore = "0.4.20"
indexmap = "1.9.3"
indoc = "2.0.1"
inquire = "0.6.2"
insta = "1.30.0"
itertools = "0.10.5"
k256 = "0.13.0"
katex = "0.4"
lsp-server = "0.7.0"
lsp-types = "0.94.0"
miette = "7.2.0"
notify = "8.2.0"
num-bigint = "0.4.4"
num-integer = "0.1.45"
num-traits = "0.2.15"
numfmt = "1.1.1"
once_cell = "1.18.0"
openssl = "0.10.80"
openssl-probe = "0.2.1"
ordinal = "0.4.0"
owo-colors = "3.5.0"
pallas-addresses = "0.35.0"
pallas-codec = "0.35.0"
pallas-crypto = "0.35.0"
pallas-primitives = "0.35.0"
pallas-traverse = "0.35.0"
patricia_tree = "0.8.0"
peg = "0.8.1"
petgraph = "0.6.3"
pretty = "0.12.3"
pretty_assertions = "1.3.0"
proptest = "1.9.0"
pulldown-cmark = "0.12.0"
rand = "0.9.2"
rayon = "1.11.0"
regex = "1.12.2"
reqwest = "0.11.14"
rgb = "0.8.50"
secp256k1 = "0.26.0"
semver = "1.0.23"
serde = "1.0.197"
serde_json = "1.0.148"
strip-ansi-escapes = "0.1.1"
strum = "0.26.3"
test-case = "3.3.1"
textplots = "0.8.7"
thiserror = "1.0.39"
tokio = "1.43.1"
toml = "1.1.0"
tracing = "0.1.44"
url = "2.5.7"
urlencoding = "2.1.2"
vec1 = "1.10.1"
walkdir = "2.3.2"
xdg = "2.5.2"
zip = "0.6.4"

uplc = { path = 'crates/uplc', version = "1.1.23" }
aiken-lang = { path = "crates/aiken-lang", version = "1.1.23" }
aiken-lsp = { path = "crates/aiken-lsp", version = "1.1.23" }
aiken-project = { path = 'crates/aiken-project', version = "1.1.23" }

[profile.dev.package.insta]
opt-level = 3

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
