[package]
name = "aiken"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
rust-version.workspace = true

[package.metadata.wix]
upgrade-guid = "288B160D-418A-4558-91B9-7C38CFD789C7"
path-guid = "4EB8FCD6-261B-4F6C-B7DB-CFA67B4E6960"
license = false
eula = false

[dependencies]
aiken-lang.workspace = true
aiken-lsp.workspace = true
aiken-project.workspace = true
clap = { workspace = true, features = ["derive", "wrap_help", "unicode", "string"] }
clap_complete.workspace = true
color-print.workspace = true
hex.workspace = true
ignore.workspace = true
indoc.workspace = true
inquire.workspace = true
miette.workspace = true
num-bigint.workspace = true
ordinal.workspace = true
owo-colors = { workspace = true, features = ["supports-colors"] }
pallas-codec.workspace = true
pallas-primitives.workspace = true
pallas-addresses.workspace = true
pallas-traverse.workspace = true
rand.workspace = true
regex.workspace = true
serde_json.workspace = true
strum = { workspace = true, features = ["derive"] }
thiserror.workspace = true
uplc.workspace = true

[target.'cfg(not(windows))'.dependencies]
xdg.workspace = true

[target.'cfg(target_env = "musl")'.dependencies]
openssl = { workspace = true, features = ["vendored"] }
openssl-probe.workspace = true
