name = 'aiken-lang/one_shot'
version = '0.0.0'
license = 'Apache-2.0'
description = "One shot parameterized minting and burning of tokens"

[repository]
user = 'aiken-lang'
project = 'one_shot'
platform = 'github'

[[dependencies]]
name = 'aiken-lang/stdlib'
version = 'main'
source = 'github'
