[package]
name = "uplc"
version.workspace = true
edition.workspace = true
description = "Utilities for working with Untyped Plutus Core"
license.workspace = true
authors = ["Lucas Rosa <x@rvcas.dev>", "Kasey White <kwhitemsg@gmail.com>"]
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
rust-version.workspace = true

exclude = ["test_data/*"]

[dependencies]
bitvec.workspace = true
blst.workspace = true
cryptoxide = { workspace = true, features = ["digest"] }
hamming.workspace = true
hex.workspace = true
indexmap.workspace = true
itertools.workspace = true
miette.workspace = true
num-bigint.workspace = true
num-integer.workspace = true
num-traits.workspace = true
once_cell.workspace = true
pallas-addresses.workspace = true
pallas-codec = { workspace = true, features = ["num-bigint"] }
pallas-crypto.workspace = true
pallas-primitives.workspace = true
pallas-traverse.workspace = true
peg.workspace = true
pretty.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
strum = { workspace = true, features = ["derive"] }
thiserror.workspace = true

[target.'cfg(not(target_family="wasm"))'.dependencies]
secp256k1.workspace = true
[target.'cfg(target_family="wasm")'.dependencies]
k256.workspace = true

[dev-dependencies]
difference.workspace = true
hex.workspace = true
indoc.workspace = true
insta = { workspace = true, features = ["yaml", "json", "redactions"] }
pretty_assertions.workspace = true
proptest.workspace = true
test-case.workspace = true
walkdir.workspace = true
