// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $index from "./routes/index.tsx";
import * as $Oneshot from "./islands/Oneshot.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Oneshot.tsx": $Oneshot,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
