#![allow(clippy::doc_overindented_list_items)]

use super::build::{trace_filter_parser, trace_level_parser};
use aiken_lang::ast::{TraceLevel, Tracing};
use aiken_project::{error::Error, options::Options, watch::with_project};
use std::{fs, path::PathBuf, process};

#[derive(clap::Args)]
#[clap(disable_version_flag(true))]
#[command(
    verbatim_doc_comment,
    about = color_print::cstr!(r#"
Export property-based tests as flat-encoded UPLC programs.

This command compiles the project and exports all property tests as JSON containing:
- The test program (as hex-encoded CBOR-wrapped flat bytes)
- The fuzzer program (as hex-encoded CBOR-wrapped flat bytes)
- The fuzzer type information (for generating test inputs)

Unit tests and benchmarks are excluded from the export.
"#),
    after_long_help = color_print::cstr!(r#"<bold><underline>Examples:</underline></bold>

    <bold>aiken export-tests</bold>
        Export all property tests to stdout

    <bold>aiken export-tests -o tests.json</bold>
        Export all property tests to tests.json

    <bold>aiken export-tests -m "my_module.test_"</bold>
        Export only property tests matching the pattern

    <bold>aiken export-tests --include-flat-bytes -o tests.json</bold>
        Export with raw flat bytes included

You are seeing the extended help. Use `-h` instead of `--help` for a more compact view.
"#
))]
pub struct Args {
    /// Path to project
    directory: Option<PathBuf>,

    /// Deny warnings; warnings will be treated as errors
    #[clap(short = 'D', long)]
    deny: bool,

    /// Silence warnings; warnings will not be printed
    #[clap(short = 'S', long)]
    silent: bool,

    /// Only export tests if they match any of these strings.
    /// You can match a module with `-m aiken/list` or `-m list`.
    /// You can match a test with `-m "aiken/list.{map}"` or `-m "aiken/option.{flatten_1}"`
    #[clap(short, long, verbatim_doc_comment)]
    match_tests: Option<Vec<String>>,

    /// This is meant to be used with `--match-tests`.
    /// It forces test names to match exactly
    #[clap(short, long)]
    exact_match: bool,

    /// Write output to the given file instead of stdout
    #[clap(short, long, value_name = "PATH")]
    output: Option<PathBuf>,

    /// Include raw flat bytes in the output (in addition to hex-encoded CBOR)
    #[clap(long)]
    include_flat_bytes: bool,

    /// Environment to build against.
    #[clap(long)]
    env: Option<String>,

    /// Filter traces to be included in the generated program(s).
    ///
    ///   - user-defined:
    ///       only consider traces that you've explicitly defined
    ///       either through the 'trace' keyword of via the trace-if-false
    ///       ('?') operator.
    ///
    ///   - compiler-generated:
    ///       only included internal traces generated by the
    ///       Aiken compiler, for example in usage of 'expect'.
    ///
    ///   - all:
    ///       include both user-defined and compiler-generated traces.
    ///
    /// [optional] [default: all]
    #[clap(short = 'f', long, value_parser=trace_filter_parser(), default_missing_value="all", verbatim_doc_comment, alias = "filter_traces")]
    trace_filter: Option<fn(TraceLevel) -> Tracing>,

    /// Choose the verbosity level of traces:
    ///
    ///   - silent:
    ///       disable traces altogether
    ///
    ///   - compact:
    ///       only culprit line numbers are shown on failures
    ///
    ///   - verbose:
    ///       enable full verbose traces as provided by the user or the compiler
    ///
    /// [optional]
    #[clap(short, long, value_parser=trace_level_parser(), default_value_t=TraceLevel::Verbose, verbatim_doc_comment)]
    trace_level: TraceLevel,
}

pub fn exec(
    Args {
        directory,
        deny,
        silent,
        match_tests,
        exact_match,
        output,
        include_flat_bytes,
        env,
        trace_filter,
        trace_level,
    }: Args,
) -> miette::Result<()> {
    with_project(directory.as_deref(), deny, silent, true, |p| {
        p.compile(Options {
            env: env.clone(),
            ..Default::default()
        })?;

        let tracing = match trace_filter {
            Some(trace_filter) => trace_filter(trace_level),
            None => Tracing::All(trace_level),
        };

        let exported =
            p.export_tests(match_tests.clone(), exact_match, tracing, include_flat_bytes)?;

        let json = serde_json::to_string_pretty(&exported).unwrap();

        match &output {
            Some(path) => {
                fs::write(path, json).map_err(|error| Error::FileIo {
                    error,
                    path: path.clone(),
                })?;
            }
            None => {
                println!("{json}");
            }
        }

        Ok(())
    })
    .map_err(|_| process::exit(1))
}
