#![allow(clippy::doc_overindented_list_items)]

use super::build::{trace_filter_parser, trace_level_parser};
use aiken_lang::ast::{TraceLevel, Tracing};
use aiken_project::{error::Error, export::ExportedTests, options::Options, watch::with_project};
use std::{
    fs,
    path::{Path, PathBuf},
    process,
};

#[derive(clap::Args)]
#[clap(disable_version_flag(true))]
#[command(
    verbatim_doc_comment,
    about = color_print::cstr!(r#"
Export property-based tests as flat-encoded UPLC programs.

This command compiles the project and exports all property tests as JSON containing:
- The test program (as hex-encoded CBOR-wrapped flat bytes)
- The fuzzer program (as hex-encoded CBOR-wrapped flat bytes)
- The fuzzer type information (for generating test inputs)

Unit tests and benchmarks are excluded from the export.
"#),
    after_long_help = color_print::cstr!(r#"<bold><underline>Examples:</underline></bold>

    <bold>aiken export-tests</bold>
        Export all property tests to stdout

    <bold>aiken export-tests -o tests.json</bold>
        Export all property tests to tests.json

    <bold>aiken export-tests -m "my_module.test_"</bold>
        Export only property tests matching the pattern

    <bold>aiken export-tests --include-flat-bytes -o tests.json</bold>
        Export with raw flat bytes included

You are seeing the extended help. Use `-h` instead of `--help` for a more compact view.
"#
))]
pub struct Args {
    /// Path to project
    directory: Option<PathBuf>,

    /// Deny warnings; warnings will be treated as errors
    #[clap(short = 'D', long)]
    deny: bool,

    /// Silence warnings; warnings will not be printed
    #[clap(short = 'S', long)]
    silent: bool,

    /// Only export tests if they match any of these strings.
    /// You can match a module with `-m aiken/list` or `-m list`.
    /// You can match a test with `-m "aiken/list.{map}"` or `-m "aiken/option.{flatten_1}"`
    #[clap(short, long, verbatim_doc_comment)]
    match_tests: Option<Vec<String>>,

    /// This is meant to be used with `--match-tests`.
    /// It forces test names to match exactly
    #[clap(short, long)]
    exact_match: bool,

    /// Write output to the given file instead of stdout
    #[clap(short, long, value_name = "PATH")]
    output: Option<PathBuf>,

    /// Include raw flat bytes in the output (in addition to hex-encoded CBOR)
    #[clap(long)]
    include_flat_bytes: bool,

    /// Environment to build against.
    #[clap(long)]
    env: Option<String>,

    /// Filter traces to be included in the generated program(s).
    ///
    ///   - user-defined:
    ///       only consider traces that you've explicitly defined
    ///       either through the 'trace' keyword of via the trace-if-false
    ///       ('?') operator.
    ///
    ///   - compiler-generated:
    ///       only included internal traces generated by the
    ///       Aiken compiler, for example in usage of 'expect'.
    ///
    ///   - all:
    ///       include both user-defined and compiler-generated traces.
    ///
    /// [optional] [default: all]
    #[clap(short = 'f', long, value_parser=trace_filter_parser(), default_missing_value="all", verbatim_doc_comment, alias = "filter_traces")]
    trace_filter: Option<fn(TraceLevel) -> Tracing>,

    /// Choose the verbosity level of traces:
    ///
    ///   - silent:
    ///       disable traces altogether
    ///
    ///   - compact:
    ///       only culprit line numbers are shown on failures
    ///
    ///   - verbose:
    ///       enable full verbose traces as provided by the user or the compiler
    ///
    /// [optional]
    #[clap(short, long, value_parser=trace_level_parser(), default_value_t=TraceLevel::Verbose, verbatim_doc_comment)]
    trace_level: TraceLevel,
}

#[derive(Clone)]
struct ExportCommandOptions {
    match_tests: Option<Vec<String>>,
    exact_match: bool,
    output: Option<PathBuf>,
    include_flat_bytes: bool,
    env: Option<String>,
    trace_filter: Option<fn(TraceLevel) -> Tracing>,
    trace_level: TraceLevel,
}

fn export_compile_options(env: Option<String>) -> Options {
    Options {
        env,
        ..Default::default()
    }
}

fn export_tracing(
    trace_filter: Option<fn(TraceLevel) -> Tracing>,
    trace_level: TraceLevel,
) -> Tracing {
    match trace_filter {
        Some(trace_filter) => trace_filter(trace_level),
        None => Tracing::All(trace_level),
    }
}

fn run_export_command_with<R, W>(
    options: ExportCommandOptions,
    mut run_export: R,
    mut write_output: W,
) -> Result<Option<String>, Vec<Error>>
where
    R: FnMut(
        Options,
        Option<Vec<String>>,
        bool,
        Tracing,
        bool,
    ) -> Result<ExportedTests, Vec<Error>>,
    W: FnMut(&Path, &str) -> std::io::Result<()>,
{
    let compile_options = export_compile_options(options.env.clone());
    let tracing = export_tracing(options.trace_filter, options.trace_level);
    let exported = run_export(
        compile_options,
        options.match_tests,
        options.exact_match,
        tracing,
        options.include_flat_bytes,
    )?;

    let json = serde_json::to_string_pretty(&exported).map_err(|e| vec![Error::from(e)])?;

    match options.output {
        Some(path) => {
            write_output(&path, &json)
                .map_err(|error| Error::FileIo {
                    error,
                    path: Box::new(path.clone()),
                })
                .map_err(|e| vec![e])?;
            Ok(None)
        }
        None => Ok(Some(json)),
    }
}

pub fn exec(
    Args {
        directory,
        deny,
        silent,
        match_tests,
        exact_match,
        output,
        include_flat_bytes,
        env,
        trace_filter,
        trace_level,
    }: Args,
) -> miette::Result<()> {
    let command_options = ExportCommandOptions {
        match_tests,
        exact_match,
        output,
        include_flat_bytes,
        env,
        trace_filter,
        trace_level,
    };

    with_project(directory.as_deref(), deny, silent, true, |p| {
        let output = run_export_command_with(
            command_options.clone(),
            |compile_options, match_tests, exact_match, tracing, include_flat_bytes| {
                p.compile(compile_options)?;
                p.export_tests(match_tests, exact_match, tracing, include_flat_bytes)
                    .map_err(|e| vec![e])
            },
            |path, json| fs::write(path, json),
        )?;

        if let Some(json) = output {
            println!("{json}");
        }

        Ok(())
    })
    .map_err(|_| process::exit(1))
}

#[cfg(test)]
mod tests {
    use super::{Args, ExportCommandOptions, run_export_command_with};
    use aiken_lang::{ast::TraceLevel, plutus_version::PlutusVersion};
    use aiken_project::{Project, error::Error, export::ExportedTests, telemetry::EventTarget};
    use clap::Parser;
    use std::{
        fs,
        path::{Path, PathBuf},
        time::SystemTime,
    };

    #[derive(Parser)]
    struct TestCli {
        #[command(flatten)]
        args: Args,
    }

    fn dummy_exported_tests() -> ExportedTests {
        serde_json::from_value(serde_json::json!({
            "version": aiken_project::export::EXPORT_TESTS_VERSION,
            "plutus_version": PlutusVersion::default(),
            "property_tests": []
        }))
        .expect("dummy exported tests JSON should deserialize")
    }

    fn sample_exported_tests() -> ExportedTests {
        serde_json::from_value(serde_json::json!({
            "version": aiken_project::export::EXPORT_TESTS_VERSION,
            "plutus_version": PlutusVersion::default(),
            "property_tests": [
                {
                    "name": "validators.sample.roundtrip",
                    "module": "validators.sample",
                    "input_path": "lib/validators/sample.ak",
                    "on_test_failure": "FailImmediately",
                    "return_mode": "void",
                    "target_kind": "validator",
                    "validator_target": {
                        "validator_module": "validators/sample",
                        "validator_name": "spend",
                        "handler_name": "spend.handler",
                        "handler_program": {
                            "hex": "f00d"
                        }
                    },
                    "test_program": {
                        "hex": "deadbeef"
                    },
                    "fuzzer_program": {
                        "hex": "cafebabe"
                    },
                    "fuzzer_type": "Fuzzer<(Int, ByteArray)>",
                    "fuzzer_output_type": {
                        "tuple": ["int", "byte_array"]
                    },
                    "constraint": {
                        "tuple": [
                            { "int_range": { "min": "0", "max": "10" } },
                            { "exact": { "byte_array": [222, 173] } }
                        ]
                    },
                    "semantics": {
                        "list": {
                            "element": {
                                "data_with_schema": {
                                    "type_name": "sample.Payload<Int>"
                                }
                            },
                            "min_len": 1,
                            "max_len": 2
                        }
                    }
                }
            ]
        }))
        .expect("sample exported tests JSON should deserialize")
    }

    fn sample_exported_tests_with_flat_bytes() -> ExportedTests {
        let mut value = serde_json::to_value(sample_exported_tests())
            .expect("sample exported tests should serialize");
        let property = &mut value["property_tests"][0];
        property["validator_target"]["handler_program"]["flat_bytes"] =
            serde_json::json!([1, 2, 3]);
        property["test_program"]["flat_bytes"] = serde_json::json!([222, 173, 190, 239]);
        property["fuzzer_program"]["flat_bytes"] = serde_json::json!([202, 254, 186, 190]);
        serde_json::from_value(value).expect("sample flat-bytes JSON should deserialize")
    }

    fn sample_command_options() -> ExportCommandOptions {
        ExportCommandOptions {
            match_tests: None,
            exact_match: false,
            output: None,
            include_flat_bytes: false,
            env: None,
            trace_filter: None,
            trace_level: TraceLevel::Verbose,
        }
    }

    fn unique_temp_dir(prefix: &str) -> PathBuf {
        let timestamp = SystemTime::now()
            .duration_since(SystemTime::UNIX_EPOCH)
            .expect("system clock should be after UNIX_EPOCH")
            .as_nanos();
        std::env::temp_dir().join(format!("{prefix}-{}-{timestamp}", std::process::id()))
    }

    fn write_unit_only_fixture(root: &Path) {
        fs::create_dir_all(root.join("validators"))
            .expect("fixture validators directory should be creatable");

        fs::write(
            root.join("aiken.toml"),
            r#"
name = "test/export_tests_unit_only_fixture"
version = "0.0.0"
plutusVersion = "v3"
description = "export-tests unit-only fixture"
"#,
        )
        .expect("fixture aiken.toml should be writable");

        fs::write(
            root.join("validators/fixture.ak"),
            r#"
test unit_smoke() {
  True
}
"#,
        )
        .expect("fixture module should be writable");
    }

    const PINNED_STDLIB_TEST_REV: &str = "10acc2499c34eb014cfb5eb71e55a93499c4cc61";
    const PINNED_FUZZ_TEST_REV: &str = "06874926ec70747f3fc4e2b9364ee9e1393441cc";

    fn write_property_fixture_manifest(root: &Path, name: &str) {
        fs::write(
            root.join("aiken.toml"),
            format!(
                r#"
name = "{name}"
version = "0.0.0"
plutusVersion = "v3"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "{stdlib_rev}"
source = "github"

[[dependencies]]
name = "aiken-lang/fuzz"
version = "{fuzz_rev}"
source = "github"
"#,
                stdlib_rev = PINNED_STDLIB_TEST_REV,
                fuzz_rev = PINNED_FUZZ_TEST_REV,
            ),
        )
        .expect("fixture aiken.toml should be writable");
    }

    fn seed_property_fixture_dependencies(root: &Path) {
        let packages_root = root.join("build/packages");
        fs::create_dir_all(packages_root.join("aiken-lang-stdlib/lib"))
            .expect("fixture stdlib package directory should be creatable");
        fs::create_dir_all(packages_root.join("aiken-lang-fuzz/lib/aiken"))
            .expect("fixture fuzz package directory should be creatable");

        fs::write(
            packages_root.join("packages.toml"),
            format!(
                r#"
[[packages]]
name = "aiken-lang/stdlib"
version = "{stdlib_rev}"
source = "github"

[[packages]]
name = "aiken-lang/fuzz"
version = "{fuzz_rev}"
source = "github"
"#,
                stdlib_rev = PINNED_STDLIB_TEST_REV,
                fuzz_rev = PINNED_FUZZ_TEST_REV,
            ),
        )
        .expect("fixture local packages manifest should be writable");

        fs::write(
            packages_root.join("aiken-lang-fuzz/lib/aiken/fuzz.ak"),
            r#"
pub fn int() -> Fuzzer<Int> {
  todo
}
"#,
        )
        .expect("fixture fuzz module should be writable");
    }

    #[test]
    fn property_fixture_manifest_pins_dependency_revisions() {
        let fixture_root = unique_temp_dir("aiken-export-tests-manifest");
        if fixture_root.exists() {
            fs::remove_dir_all(&fixture_root).expect("stale fixture root should be removable");
        }
        fs::create_dir_all(&fixture_root).expect("fixture root should be creatable");
        write_property_fixture_manifest(&fixture_root, "test/export_tests_manifest_fixture");

        let manifest = fs::read_to_string(fixture_root.join("aiken.toml"))
            .expect("fixture manifest should exist");
        assert!(manifest.contains(PINNED_STDLIB_TEST_REV));
        assert!(manifest.contains(PINNED_FUZZ_TEST_REV));
        assert!(!manifest.contains("version = \"main\""));

        fs::remove_dir_all(fixture_root).expect("fixture root should be removable");
    }

    fn write_equality_fixture(root: &Path) {
        fs::create_dir_all(root.join("lib")).expect("fixture lib directory should be creatable");
        write_property_fixture_manifest(root, "test/export_tests_equality_fixture");
        seed_property_fixture_dependencies(root);

        fs::write(
            root.join("lib/tests.ak"),
            r#"
use aiken/fuzz

test equality_bool_export(x via fuzz.int()) {
  x == x
}
"#,
        )
        .expect("fixture module should be writable");
    }

    fn write_order_fixture(root: &Path) {
        fs::create_dir_all(root.join("lib")).expect("fixture lib directory should be creatable");
        write_property_fixture_manifest(root, "test/export_tests_order_fixture");
        seed_property_fixture_dependencies(root);

        fs::write(
            root.join("lib/b.ak"),
            r#"
use aiken/fuzz

test prop_b(x via fuzz.int()) {
  x == x
}
"#,
        )
        .expect("fixture module should be writable");

        fs::write(
            root.join("lib/a.ak"),
            r#"
use aiken/fuzz

test prop_a(x via fuzz.int()) {
  x == x
}
"#,
        )
        .expect("fixture module should be writable");
    }

    #[test]
    fn parses_export_tests_flags() {
        let cli = TestCli::parse_from([
            "aiken",
            "--output",
            "tests.json",
            "--include-flat-bytes",
            "--exact-match",
            "--match-tests",
            "validators/foo.{bar}",
            "--env",
            "staging",
        ]);

        assert_eq!(cli.args.output, Some(PathBuf::from("tests.json")));
        assert!(cli.args.include_flat_bytes);
        assert!(cli.args.exact_match);
        assert_eq!(
            cli.args.match_tests,
            Some(vec!["validators/foo.{bar}".to_string()])
        );
        assert_eq!(cli.args.env, Some("staging".to_string()));
    }

    #[test]
    fn export_command_forwards_env_to_compile_options() {
        let mut options = sample_command_options();
        options.env = Some("staging".to_string());

        let mut captured_env = None;
        let _ = run_export_command_with(
            options,
            |compile_options, _match_tests, _exact_match, _tracing, _include_flat_bytes| {
                captured_env = compile_options.env;
                Ok(dummy_exported_tests())
            },
            |_path, _json| Ok(()),
        )
        .expect("export command should compile and export successfully");

        assert_eq!(captured_env.as_deref(), Some("staging"));
    }

    #[test]
    fn export_command_forwards_include_flat_bytes_flag() {
        let mut options = sample_command_options();
        options.include_flat_bytes = true;

        let mut captured_include_flat_bytes = None;
        let _ = run_export_command_with(
            options,
            |_compile_options, _match_tests, _exact_match, _tracing, include_flat_bytes| {
                captured_include_flat_bytes = Some(include_flat_bytes);
                Ok(dummy_exported_tests())
            },
            |_path, _json| Ok(()),
        )
        .expect("export command should compile and export successfully");

        assert_eq!(captured_include_flat_bytes, Some(true));
    }

    #[test]
    fn exported_tests_json_contract_snapshot() {
        let tests = sample_exported_tests();
        insta::assert_json_snapshot!("exported_tests_json_contract", &tests);
    }

    #[test]
    fn export_command_returns_json_for_stdout_output() {
        let options = sample_command_options();
        let mut write_called = false;

        let output = run_export_command_with(
            options,
            |_compile_options, _match_tests, _exact_match, _tracing, _include_flat_bytes| {
                Ok(dummy_exported_tests())
            },
            |_path, _json| -> std::io::Result<()> {
                write_called = true;
                Ok(())
            },
        )
        .expect("export command should serialize stdout JSON");

        assert!(
            output.is_some(),
            "stdout mode should return serialized JSON payload"
        );
        assert!(!write_called, "stdout mode must not attempt file writes");
    }

    #[test]
    fn export_command_writes_json_to_file_when_output_is_set() {
        let temp_dir = unique_temp_dir("aiken-export-tests-output");
        if temp_dir.exists() {
            fs::remove_dir_all(&temp_dir).expect("stale temp dir should be removable");
        }
        fs::create_dir_all(&temp_dir).expect("temp dir should be creatable");
        let output_path = temp_dir.join("tests.json");

        let mut options = sample_command_options();
        options.output = Some(output_path.clone());
        let mut write_called = false;

        let output = run_export_command_with(
            options,
            |_compile_options, _match_tests, _exact_match, _tracing, _include_flat_bytes| {
                Ok(dummy_exported_tests())
            },
            |path, json| {
                write_called = true;
                fs::write(path, json)
            },
        )
        .expect("export command should write output JSON");

        assert!(output.is_none(), "file mode should suppress stdout output");
        assert!(write_called, "file mode should write to disk");

        let written = fs::read_to_string(&output_path).expect("written JSON should be readable");
        let parsed: serde_json::Value =
            serde_json::from_str(&written).expect("written JSON should parse");
        assert_eq!(
            parsed["property_tests"].as_array().map(|tests| tests.len()),
            Some(0),
            "fixture payload should include the serialized property_tests array"
        );

        fs::remove_dir_all(temp_dir).expect("temp dir should be removable");
    }

    #[test]
    fn exported_tests_json_uses_expected_wire_forms_and_relative_paths() {
        let value = serde_json::to_value(sample_exported_tests())
            .expect("sample exported tests should serialize");
        let property = &value["property_tests"][0];

        assert_eq!(
            value["version"],
            aiken_project::export::EXPORT_TESTS_VERSION
        );
        assert_eq!(property["input_path"], "lib/validators/sample.ak");
        assert_eq!(property["return_mode"], "void");
        assert_eq!(property["target_kind"], "validator");
        assert_eq!(
            property["fuzzer_output_type"],
            serde_json::json!({
                "tuple": ["int", "byte_array"]
            })
        );
        assert_eq!(property["on_test_failure"], "FailImmediately");
        assert!(
            property["validator_target"]["handler_program"]
                .get("flat_bytes")
                .is_none(),
            "default export JSON must omit handler flat_bytes without --include-flat-bytes"
        );
        assert!(
            property["test_program"].get("flat_bytes").is_none(),
            "default export JSON must omit test_program flat_bytes without --include-flat-bytes"
        );
        assert!(
            property["fuzzer_program"].get("flat_bytes").is_none(),
            "default export JSON must omit fuzzer_program flat_bytes without --include-flat-bytes"
        );
        assert_eq!(
            property["constraint"],
            serde_json::json!({
                "tuple": [
                    { "int_range": { "min": "0", "max": "10" } },
                    { "exact": { "byte_array": [222, 173] } }
                ]
            })
        );
        assert_eq!(
            property["semantics"],
            serde_json::json!({
                "list": {
                    "element": {
                        "data_with_schema": {
                            "type_name": "sample.Payload<Int>"
                        }
                    },
                    "min_len": 1,
                    "max_len": 2
                }
            })
        );
    }

    #[test]
    fn exported_tests_json_includes_flat_bytes_when_present() {
        let value = serde_json::to_value(sample_exported_tests_with_flat_bytes())
            .expect("sample flat-bytes tests should serialize");
        let property = &value["property_tests"][0];

        assert_eq!(
            property["validator_target"]["handler_program"]["flat_bytes"],
            serde_json::json!([1, 2, 3])
        );
        assert_eq!(
            property["test_program"]["flat_bytes"],
            serde_json::json!([222, 173, 190, 239])
        );
        assert_eq!(
            property["fuzzer_program"]["flat_bytes"],
            serde_json::json!([202, 254, 186, 190])
        );
    }

    #[test]
    fn export_command_omits_unit_only_projects_without_crashing() {
        let fixture_root = unique_temp_dir("aiken-export-tests-unit-only");
        if fixture_root.exists() {
            fs::remove_dir_all(&fixture_root).expect("stale fixture root should be removable");
        }
        fs::create_dir_all(&fixture_root).expect("fixture root should be creatable");
        write_unit_only_fixture(&fixture_root);

        let mut project = Project::new(fixture_root.clone(), EventTarget::default())
            .expect("fixture project should load");
        let output = run_export_command_with(
            sample_command_options(),
            |compile_options, match_tests, exact_match, tracing, include_flat_bytes| {
                project.compile(compile_options)?;
                project
                    .export_tests(match_tests, exact_match, tracing, include_flat_bytes)
                    .map_err(|e| vec![e])
            },
            |_path, _json| Ok(()),
        )
        .expect("unit-only projects should export without crashing");

        let json = output.expect("stdout mode should return serialized JSON payload");
        let value: serde_json::Value =
            serde_json::from_str(&json).expect("exported JSON should parse");
        assert_eq!(value["property_tests"], serde_json::json!([]));

        fs::remove_dir_all(fixture_root).expect("fixture root should be removable");
    }

    #[test]
    fn export_command_matching_a_unit_test_does_not_warn_suspicious_match() {
        let fixture_root = unique_temp_dir("aiken-export-tests-unit-match");
        if fixture_root.exists() {
            fs::remove_dir_all(&fixture_root).expect("stale fixture root should be removable");
        }
        fs::create_dir_all(&fixture_root).expect("fixture root should be creatable");
        write_unit_only_fixture(&fixture_root);

        let mut project = Project::new(fixture_root.clone(), EventTarget::default())
            .expect("fixture project should load");
        project
            .compile(super::export_compile_options(None))
            .expect("fixture project should compile");

        let exported = project
            .export_tests(
                Some(vec!["unit_smoke".to_string()]),
                true,
                aiken_lang::ast::Tracing::silent(),
                false,
            )
            .expect("matching a real unit test should not fail export");

        assert!(
            exported.property_tests.is_empty(),
            "unit-test selectors should still export no property tests",
        );
        assert!(
            !project.warnings().into_iter().any(|warning| matches!(
                warning,
                aiken_project::error::Warning::SuspiciousTestMatch { .. }
            )),
            "matching a real unit test should not emit a suspicious selector warning",
        );

        fs::remove_dir_all(fixture_root).expect("fixture root should be removable");
    }

    #[test]
    fn export_command_reports_equality_properties_as_bool() {
        let fixture_root = unique_temp_dir("aiken-export-tests-equality");
        if fixture_root.exists() {
            fs::remove_dir_all(&fixture_root).expect("stale fixture root should be removable");
        }
        fs::create_dir_all(&fixture_root).expect("fixture root should be creatable");
        write_equality_fixture(&fixture_root);

        let mut project = Project::new(fixture_root.clone(), EventTarget::default())
            .expect("fixture project should load");
        let output = run_export_command_with(
            sample_command_options(),
            |compile_options, match_tests, exact_match, tracing, include_flat_bytes| {
                project.compile(compile_options)?;
                project
                    .export_tests(match_tests, exact_match, tracing, include_flat_bytes)
                    .map_err(|e| vec![e])
            },
            |_path, _json| Ok(()),
        )
        .expect("equality fixture should export successfully");

        let json = output.expect("stdout mode should return serialized JSON payload");
        let value: serde_json::Value =
            serde_json::from_str(&json).expect("exported JSON should parse");
        assert_eq!(value["property_tests"][0]["return_mode"], "bool");

        fs::remove_dir_all(fixture_root).expect("fixture root should be removable");
    }

    #[test]
    fn export_command_sorts_property_tests_deterministically() {
        let fixture_root = unique_temp_dir("aiken-export-tests-order");
        if fixture_root.exists() {
            fs::remove_dir_all(&fixture_root).expect("stale fixture root should be removable");
        }
        fs::create_dir_all(&fixture_root).expect("fixture root should be creatable");
        write_order_fixture(&fixture_root);

        let mut project = Project::new(fixture_root.clone(), EventTarget::default())
            .expect("fixture project should load");
        let output = run_export_command_with(
            sample_command_options(),
            |compile_options, match_tests, exact_match, tracing, include_flat_bytes| {
                project.compile(compile_options)?;
                project
                    .export_tests(match_tests, exact_match, tracing, include_flat_bytes)
                    .map_err(|e| vec![e])
            },
            |_path, _json| Ok(()),
        )
        .expect("order fixture should export successfully");

        let json = output.expect("stdout mode should return serialized JSON payload");
        let value: serde_json::Value =
            serde_json::from_str(&json).expect("exported JSON should parse");
        let property_tests = value["property_tests"]
            .as_array()
            .expect("property_tests should be an array");

        assert_eq!(property_tests.len(), 2);
        assert_eq!(property_tests[0]["module"], "a");
        assert_eq!(property_tests[0]["name"], "a.prop_a");
        assert_eq!(property_tests[1]["module"], "b");
        assert_eq!(property_tests[1]["name"], "b.prop_b");

        fs::remove_dir_all(fixture_root).expect("fixture root should be removable");
    }

    #[test]
    fn export_command_reports_file_write_errors_with_output_path() {
        let temp_dir = unique_temp_dir("aiken-export-tests-error");
        if temp_dir.exists() {
            fs::remove_dir_all(&temp_dir).expect("stale temp dir should be removable");
        }
        fs::create_dir_all(&temp_dir).expect("temp dir should be creatable");
        let output_path = temp_dir.join("missing").join("tests.json");

        let mut options = sample_command_options();
        options.output = Some(output_path.clone());

        let mut errors = run_export_command_with(
            options,
            |_compile_options, _match_tests, _exact_match, _tracing, _include_flat_bytes| {
                Ok(dummy_exported_tests())
            },
            |path, json| fs::write(path, json),
        )
        .expect_err("export command should surface file write errors");

        assert_eq!(errors.len(), 1, "expected one file write error");
        match errors.pop().expect("expected one error") {
            Error::FileIo { path, .. } => assert_eq!(path, Box::new(output_path)),
            other => panic!("expected file IO error, got {other:?}"),
        }

        fs::remove_dir_all(temp_dir).expect("temp dir should be removable");
    }
}
