name = "aiken-lang/acceptance_test_096"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'aiken-lang/096'"

[repository]
user = "aiken-lang"
project = "096"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "main"
source = "github"
