[package]
name = "aiken-lang"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
rust-version.workspace = true

build = "build.rs"

[dependencies]
blst.workspace = true
cryptoxide = { workspace = true, features = ["digest"] }
hex.workspace = true
indexmap.workspace = true
indoc.workspace = true
itertools.workspace = true
miette.workspace = true
num-bigint.workspace = true
ordinal.workspace = true
owo-colors = { workspace = true, features = ["supports-colors"] }
pallas-primitives.workspace = true
patricia_tree.workspace = true
petgraph.workspace = true
pretty.workspace = true
serde = { workspace = true, features = ["derive", "rc"] }
strum = { workspace = true, features = ["derive"] }
thiserror.workspace = true
uplc.workspace = true
vec1.workspace = true

[target.'cfg(not(target_family="wasm"))'.dependencies]
chumsky = { workspace = true, features = ["default"] }
[target.'cfg(target_family="wasm")'.dependencies]
chumsky = { workspace = true, features = ["ahash", "std"] }

[dev-dependencies]
indoc.workspace = true
insta = { workspace = true, features = ["yaml", "json", "redactions"] }
pretty_assertions.workspace = true
proptest.workspace = true

[build-dependencies]
built = { workspace = true, features = ["git2"] }
