[package]
name = "aiken-project"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
rust-version.workspace = true

build = "build.rs"

[dependencies]
aiken-lang.workspace = true
askama = { workspace = true, features = ["urlencode"] }
camino.workspace = true
ciborium.workspace = true
dirs.workspace = true
fslock.workspace = true
futures.workspace = true
glob.workspace = true
hex.workspace = true
ignore.workspace = true
indexmap.workspace = true
indoc.workspace = true
itertools.workspace = true
miette = { workspace = true, features = ["fancy"] }
notify.workspace = true
num-bigint.workspace = true
numfmt.workspace = true
ordinal.workspace = true
owo-colors = { workspace = true, features = ["supports-colors"] }
pallas-addresses.workspace = true
pallas-codec.workspace = true
pallas-crypto.workspace = true
pallas-primitives.workspace = true
pallas-traverse.workspace = true
petgraph.workspace = true
pulldown-cmark = { workspace = true, features = ["html"] }
rayon.workspace = true
regex.workspace = true
reqwest = { workspace = true, features = ["blocking", "json"] }
rgb.workspace = true
semver = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["preserve_order"] }
strip-ansi-escapes.workspace = true
textplots.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["full"] }
toml.workspace = true
uplc.workspace = true
vec1.workspace = true
walkdir.workspace = true
zip.workspace = true

[target.'cfg(not(windows))'.dependencies]
katex.workspace = true

[dev-dependencies]
blst.workspace = true
indoc.workspace = true
insta = { workspace = true, features = ["yaml", "json", "redactions"] }
proptest.workspace = true
pretty_assertions.workspace = true

[build-dependencies]
built.workspace = true
