[package]
name = "aiken-lsp"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
rust-version.workspace = true

[dependencies]
aiken-lang.workspace = true
aiken-project.workspace = true
crossbeam-channel.workspace = true
indoc.workspace = true
itertools.workspace = true
lsp-server.workspace = true
lsp-types.workspace = true
miette.workspace = true
owo-colors = { workspace = true, features = ["supports-colors"] }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
url.workspace = true
urlencoding.workspace = true
