name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose --workspace
    - name: Run unit tests
      run: cargo test --verbose --workspace
    - name: Run acceptance tests
      working-directory: examples/acceptance_tests
      run: for scenario in $(find . -maxdepth 1 -mindepth 1 -type d); bash run -- $scenario;
      shell: bash
    - name: Format
      run: cargo fmt --all -- --check
    - name: Clippy
      run: cargo clippy --all-targets --all-features -- -D warnings
